<style>

div.on {
	display: block;
}

div.off {
	display: none;
}

</style>

<div class="row off" id="FechaDeVenta">

<!--
<div style="background-color:white; width:100%;height:145px;overflow-y:scroll;overflow-x:hidden; font-size:12px;">
	<div role="tabpanel">
  		<ul class="nav nav-tabs" role="tablist">
    			<li role="presentation" class="active"><a href="#f1" aria-controls="f1" role="tab" data-toggle="tab">Software</a></li>
    			<li role="presentation"><a href="#f2" aria-controls="f2" role="tab" data-toggle="tab">Pago</a></li>
    			<li role="presentation"><a href="#f3" aria-controls="f3" role="tab" data-toggle="tab">Datos</a></li>
    			<li role="presentation"><a href="#f4" aria-controls="f4" role="tab" data-toggle="tab">Referencias</a></li>
    			<li role="presentation"><a href="#f5" aria-controls="f5" role="tab" data-toggle="tab">Usuario</a></li>
    			<li role="presentation"><a href="#f6" aria-controls="f6" role="tab" data-toggle="tab">Pagos</a></li>
  		</ul>
  		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="f1">
				<div class="row">
					<div class="col-md-3">
						<b>Fecha de venta:</b><br>
						<div class="input-group input-group-md" style="width:150px;">
						<input type="text" id="datepickerfechaventa" name="fechaventa" onlyread="onlyread" class="form-control">
						</div>
					</div>
					<div class="col-md-2">
						<b>Monto de Venta:</b><br><input type="text"  name="montodeventa" class="form-control">
					</div>
					<div class="col-md-3">
						<b>Software:</b><br>
						<select name="softwarevendido" class="form-control" id="">
							<option value=""></option>
							<option value="InteriCAD Lite">InteriCAD Lite</option>
							<option value="InteriCAD 8000">InteriCAD 8000</option>
							<option value="InteriCAD T6">InteriCAD T6</option>
							<option value="KD MAX">KD MAX</option>
							<option value="Ceramic King">Ceramic King</option>
							<option value="iScan">iScan</option>
						</select>
					</div>
					<div class="col-md-2">
						<b>Version:</b><br><input type="text" name="fd_version" class="form-control" placeholder="version" value="<?= $version ?>">
					</div>
					<div class="col-md-2"><b>Numero_de_serie:</b><br><input type="text" name="fd_numero_de_serie" class="form-control" placeholder="numero_de_serie" value="<?= $numero_de_serie ?>"></div>
				</div>
				<div class="row" style="margin-top:2px;">
					<div class="col-md-3"><b>Codigos_de_activacion:</b><br><input type="text" name="fd_codigos_de_activacion" class="form-control" placeholder="codigos_de_activacion" value="<?= $codigos_de_activacion ?>"></div>
					<div class="col-md-3"><b>Licencía:</b><br>
						<select name="asignacion_licencia" id="" class="form-control" >
							<option value="1">1 Mes</option>
							<option value="3">3 Meses</option>
							<option value="6">6 Meses</option>
							<option value="9">9 Meses</option>
							<option value="12">12 Meses</option>
						</select>
					</div>
					<div class="col-md-3"><b>Desde:</b><br>
						<div class="input-group input-group-md" style="width:100px;">
						<input type="text" id="datepickerasignacion_fecha_inicial" name="q4_fecha_inicial" onlyread="onlyread" class="form-control">
						</div>
					</div>
					<div class="col-md-3"><b>Hasta:</b><br>
						<div class="input-group input-group-md" style="width:100px;">
						<input type="text" id="datepickerasignacion_fecha_final" name="q4_fecha_final" onlyread="onlyread" class="form-control">
						</div>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="f2">
				<div class="row">
					<div class="col-md-4"><b>Precio_total:</b><br><input type="text" name="fd_precio_total" class="form-control" placeholder="precio_total" value="<?= $precio_total ?>"></div>
					<div class="col-md-4"><b>Precio_sin_iva:</b><br><input type="text" name="fd_precio_sin_iva" class="form-control" placeholder="precio_sin_iva" value="<?= $precio_sin_iva ?>"></div>
					<div class="col-md-4"><b>Forma_de_pago:</b><br><input type="text" name="fd_forma_de_pago" class="form-control" placeholder="forma_de_pago" value="<?= $forma_de_pago ?>"></div>
				</div>
				<div class="row" style="margin-top:2px;">
					<div class="col-md-4"><b>Cantidad_mensual:</b><br><input type="text" name="fd_cantidad_mensual" class="form-control" placeholder="cantidad_mensual" value="<?= $cantidad_mensual ?>"></div>
					<div class="col-md-4"><b>Banco_:</b><br><input type="text" name="fd_banco_" class="form-control" placeholder="banco_" value="<?= $banco_ ?>"></div>
					<div class="col-md-4"><b>Factura_avance:</b><br><input type="text" name="fd_factura_avance" class="form-control" placeholder="factura_avance" value="<?= $factura_avance ?>"></div>
				</div>				
			</div>
			<div role="tabpanel" class="tab-pane" id="f3">
				<div class="row">
					<div class="col-md-3"><b>Documentacion:</b><br><input type="text" name="fd_documentacion" class="form-control" placeholder="documentacion" value="<?= $documentacion ?>"></div>
					<div class="col-md-3"><b>Razon_social:</b><br><input type="text" name="fd_razon_social" class="form-control" placeholder="razon_social" value="<?= $razon_social ?>"></div>
					<div class="col-md-2"><b>Rfc:</b><br><input type="text" name="fd_rfc" class="form-control" placeholder="rfc" value="<?= $rfc ?>"></div>
					<div class="col-md-2"><b>Domicilio_fiscal:</b><br><input type="text" name="fd_domicilio_fiscal" class="form-control" placeholder="domicilio_fiscal" value="<?= $domicilio_fiscal ?>"></div>
					<div class="col-md-2"><b>Cp:</b><br><input type="text" name="fd_cp" class="form-control" placeholder="cp" value="<?= $cp ?>"></div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="f4">
				<div class="row">
					<div class="col-md-3"><b>Ref_nombre1:</b><br><input type="text" name="fd_ref_nombre1" class="form-control" placeholder="ref_nombre1" value="<?= $ref_nombre1 ?>"></div>
					<div class="col-md-3"><b>Ref_tel1:</b><br><input type="text" name="fd_ref_tel1" class="form-control" placeholder="ref_tel1" value="<?= $ref_tel1 ?>"></div>
					<div class="col-md-3"><b>Ref_mail1:</b><br><input type="text" name="fd_ref_mail1" class="form-control" placeholder="ref_mail1" value="<?= $ref_mail1 ?>"></div>
					<div class="col-md-3"><b>Ref_parentezco1:</b><br><input type="text" name="fd_ref_parentezco1" class="form-control" placeholder="ref_parentezco1" value="<?= $ref_parentezco1 ?>"></div>
				</div>
				<div class="row" style="margin-top:2px;">
					<div class="col-md-3"><b>Ref_nombre2:</b><br><input type="text" name="fd_ref_nombre2" class="form-control" placeholder="ref_nombre2" value="<?= $ref_nombre2 ?>"></div>
					<div class="col-md-3"><b>Ref_tel2:</b><br><input type="text" name="fd_ref_tel2" class="form-control" placeholder="ref_tel2" value="<?= $ref_tel2 ?>"></div>
					<div class="col-md-3"><b>Ref_mail2:</b><br><input type="text" name="fd_ref_mail2" class="form-control" placeholder="ref_mail2" value="<?= $ref_mail2 ?>"></div>
					<div class="col-md-3"><b>Ref_parentezco2:</b><br><input type="text" name="fd_ref_parentezco2" class="form-control" placeholder="ref_parentezco2" value="<?= $ref_parentezco2 ?>"></div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="f5">
				<div class="row">
					<div class="col-md-4"><b>Nombre_de_usuario:</b><br><input type="text" name="fd_nombre_de_usuario" class="form-control" placeholder="nombre_de_usuario" value="<?= $nombre_de_usuario ?>"></div>
					<div class="col-md-4"><b>Email_de_usuario:</b><br><input type="text" name="fd_email_de_usuario" class="form-control" placeholder="email_de_usuario" value="<?= $email_de_usuario ?>"></div>
					<div class="col-md-4"><b>Tel_usuario:</b><br><input type="text" name="fd_tel_usuario" class="form-control" placeholder="tel_usuario" value="<?= $tel_usuario ?>"></div>
				</div>
				<div class="row" style="margin-top:2px;">
					<div class="col-md-4"><b>Experiencia_en_software_cad:</b><br><input type="text" name="fd_experiencia_en_software_cad" class="form-control" placeholder="experiencia_en_software_cad" value="<?= $experiencia_en_software_cad ?>"></div>
					<div class="col-md-4"><b>Software_que_utiliza:</b><br><input type="text" name="fd_software_que_utiliza" class="form-control" placeholder="software_que_utiliza" value="<?= $software_que_utiliza ?>"></div>
					<div class="col-md-4"><b>Sistema_operativo:</b><br><input type="text" name="fd_sistema_operativo" class="form-control" placeholder="sistema_operativo" value="<?= $sistema_operativo ?>"></div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="f6">
				<div class="row">
					<div class="col-md-3"><b>Nombre_de_pagos:</b><br><input type="text" name="fd_nombre_de_pagos" class="form-control" placeholder="nombre_de_pagos" value="<?= $nombre_de_pagos ?>"></div>
					<div class="col-md-3"><b>Tel_pagos:</b><br><input type="text" name="fd_tel_pagos" class="form-control" placeholder="tel_pagos" value="<?= $tel_pagos ?>"></div>
					<div class="col-md-3"><b>Mail_pagos:</b><br><input type="text" name="fd_mail_pagos" class="form-control" placeholder="mail_pagos" value="<?= $mail_pagos ?>"></div>
					<div class="col-md-3"><b>Notas:</b><br><input type="text" name="fd_notas" class="form-control" placeholder="notas" value="<?= $notas ?>"></div>
				</div>
				<div class="row" style="margin-top:2px;">
					<div class="col-md-4"><b>Modelado_de_objetos:</b><br><input type="text" name="fd_modelado_de_objetos" class="form-control" placeholder="modelado_de_objetos" value="<?= $modelado_de_objetos ?>"></div>
					<div class="col-md-4"><b>Fecha_entrega_objetos:</b><br><input type="text" name="fd_fecha_entrega_objetos" class="form-control" placeholder="fecha_entrega_objetos" value="<?= $fecha_entrega_objetos ?>"></div>
					<div class="col-md-4"><b>Puntos_interimodel:</b><br><input type="text" name="fd_puntos_interimodel" class="form-control" placeholder="puntos_interimodel" value="<?= $puntos_interimodel ?>"></div>
				</div>
			</div>
  		</div>
	</div>
</div>
-->

</div>
<br>

<script>
	$('#myTab a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
</script>