<div class="row">
  	<div class="col-xs-5 col-sm-5 col-md-5">
  		<h4>
  			&nbsp;<span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> 
  			Próxima llamada: <?= $id ?>
  		</h4>
			
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="input-group input-group-md" style="width:200px;">
					<input type="text" id="datepicker" name="fechaprox" onlyread="onlyread" class="form-control">
				</div>
				<br>
				<input type="hidden" name="horaAgenda" value="01">
  				<input type="hidden" name="minutoAgenda" value="01">
  				<input type="hidden" name="ampmAgenda" value="AM">
  				<select name="" class="form-control">
					<option value="7:00 AM">7:00 AM</option>
					<option value="7:30 AM">7:30 AM</option>
					<option value="8:00 AM">8:00 AM</option>
					<option value="8:30 AM">8:30 AM</option>
					<option value="9:00 AM">9:00 AM</option>
					<option value="9:30 AM">9:30 AM</option>
					<option value="10:00 AM">10:00 AM</option>
					<option value="10:30 AM">10:30 AM</option>
					<option value="11:00 AM">11:00 AM</option>
					<option value="11:30 AM">11:30 AM</option>
					<option value="12:00 PM">12:00 PM</option>
					<option value="12:30 PM">12:30 PM</option>
					<option value="1:00 PM">1:00 PM</option>
					<option value="1:30 PM">1:30 PM</option>
					<option value="2:00 PM">2:00 PM</option>
					<option value="2:30 PM">2:30 PM</option>
					<option value="3:00 PM">3:00 PM</option>
					<option value="3:30 PM">3:30 PM</option>
					<option value="4:00 PM">4:00 PM</option>
					<option value="4:30 PM">4:30 PM</option>
					<option value="5:00 PM">5:00 PM</option>
					<option value="5:30 PM">5:30 PM</option>
					<option value="6:00 PM">6:00 PM</option>
					<option value="6:30 PM">6:30 PM</option>
					<option value="7:00 PM">7:00 PM</option>
				</select>
			</div>
		</div>
  	</div>
  	<div class="col-xs-6 col-sm-6 col-md-6">
  		<?php
  			ini_set('date.timezone', 'America/Chihuahua');
    			$tiempoChihuahua = date('ym', gmdate('U'));
  		?>
		 <iframe src="iframe-calendario.php?id=<?= $id ?>&calendar=<?= $tiempoChihuahua ?>#<?= $tiempoChihuahua ?>" width="300" height="200" frameborder="0"></iframe> 
  			<!--
  					$conexion = mysql_connect("$dbh", "$dbu", "$dbp") or trigger_error(mysql_error(),E_USER_ERROR); 
					mysql_select_db("$dbn", $conexion);
					mysql_query("SET NAMES 'utf8'");
  					# include('inc/calendar.1507.php');
  			-->
  	</div>
  	<div class="col-xs-1 col-sm-1 col-md-1"></div>
</div>
<!-- <input type="time" name="fechaprox211" step="1" class="form-control"> -->
<br>