<table class="table table-striped" style="width:100%;">
	<tr>
		<th>
			<a href="#f1" aria-controls="f1" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> General
				</button>
			</a>
		</th>
		<th>
			<a href="#f2" aria-controls="f2" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Terminos de venta
				</button>
			</a>
		</th>
		<th>
			<a href="#f3" aria-controls="f3" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Usuarios
				</button>
			</a>
		</th>
		<th>
			<a href="#f4" aria-controls="f4" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Datos de Facturación
				</button>
			</a>
		</th>
		<th>
			<a href="#f5" aria-controls="f5" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-info">
					<span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span> Referencias
				</button>
			</a>
		</th>
	</tr>
</table>
<div class="row">
<div class="col-md-6">
	<table class="table table-bordered table-striped">
		<tr>
			<th>
				Nombre
			</th>
			<td>
				<input type="text" name="fd_ref_nombre1" class="form-control" placeholder="" value="<?= $ref_nombre1 ?>">
			</td>
		</tr>
		<tr>
			<th>
				Tel
			</th>
			<td>
				<input type="text" name="fd_ref_tel1" class="form-control" placeholder="" value="<?= $ref_tel1 ?>">
			</td>
		</tr>
		<tr>
			<th>
				Mail
			</th>
			<td>
				<input type="text" name="fd_ref_mail1" class="form-control" placeholder="" value="<?= $ref_mail1 ?>">
			</td>
		</tr>
		<tr>
			<th>
				Parentezco
			</th>
			<td>
				<input type="text" name="fd_ref_parentezco1" class="form-control" placeholder="" value="<?= $ref_parentezco1 ?>">
			</td>
		</tr>
	</table>
</div>
<div class="col-md-6">
	<table class="table table-bordered table-striped">
		<tr>
			<th>
				Nombre
			</th>
			<td>
				<input type="text" name="fd_ref_nombre2" class="form-control" placeholder="" value="<?= $ref_nombre2 ?>">
			</td>
		</tr>
		<tr>
			<th>
				Tel
			</th>
			<td>
				<input type="text" name="fd_ref_tel2" class="form-control" placeholder="" value="<?= $ref_tel2 ?>">
			</td>
		</tr>
		<tr>
			<th>
				Mail
			</th>
			<td>
				<input type="text" name="fd_ref_mail2" class="form-control" placeholder="" value="<?= $ref_mail2 ?>">
			</td>
		</tr>
		<tr>
			<th>
				Parentezco
			</th>
			<td>
				<input type="text" name="fd_ref_parentezco2" class="form-control" placeholder="" value="<?= $ref_parentezco2 ?>">
			</td>
		</tr>
	</table>
	<center>
			
				<button type="button" class="btn btn-success" aria-label="Left Align" data-dismiss="modal">
					<span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span> Siguiente
				</button>	
			
		</center>
</div>
</div>