<input type="hidden" name="fd_razon_social" class="form-control" placeholder="" value="OFF">
<input type="hidden" name="fd_rfc" class="form-control" placeholder="" value="OFF">
<input type="hidden" name="fd_domicilio_fiscal" class="form-control" placeholder="" value="OFF">
<input type="hidden" name="fd_cp" class="form-control" placeholder="" value="OFF">
<input type="hidden" name="fd_nombre_de_pagos" class="form-control" placeholder="" value="OFF">
<input type="hidden" name="fd_tel_pagos" class="form-control" placeholder="" value="OFF">
<input type="hidden" name="fd_mail_pagos" class="form-control" placeholder="" value="OFF">
<input type="hidden" name="fd_notas" class="form-control" placeholder="" value="OFF">

<table class="table table-striped" style="width:100%;">
	<tr>
		<th>
			<a href="#f1" aria-controls="f1" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> General
				</button>
			</a>
		</th>
		<th>
			<a href="#f2" aria-controls="f2" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Terminos de venta
				</button>
			</a>
		</th>
		<th>
			<a href="#f3" aria-controls="f3" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Usuarios
				</button>
			</a>
		</th>
		<th>
			<a href="#f4" aria-controls="f4" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-info">
					<span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span> Datos de Facturación
				</button>
			</a>
		</th>
		<th>
			<a href="#f5" aria-controls="f5" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-default">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Referencias
				</button>
			</a>
		</th>
	</tr>
</table>


<div class="row">
	<div class="col-md-4">
		<table class="table table-bordered table-striped">
			<tr>
				<th>
					Razón Social
				</th>
				<td>
					<input type="text" name="ddf_razon_social" class="form-control" placeholder="" value="">
				</td>
			</tr>
			<tr>
				<th>
					RFC
				</th>
				<td>
					<input type="text" name="ddf_rfc" class="form-control" placeholder="" value="">
				</td>
			</tr>
			<tr>
				<th>
					Calle
				</th>
				<td>
					<input type="text" name="ddf_calle" class="form-control" placeholder="" value="">
				</td>
			</tr>
			<tr>
				<th>
					No. Exterior
				</th>
				<td>
					<input type="text" name="ddf_num_exterior" class="form-control" placeholder="" value="">
				</td>
			</tr>
		</table>
	</div>
	<div class="col-md-4">
		<table class="table table-bordered table-striped">
			<tr>
				<th>
					No. Interior
				</th>
				<td>
					<input type="text" name="ddf_num_interior" class="form-control" placeholder="" value="">
				</td>
			</tr>
			<tr>
				<th>
					Colonia
				</th>
				<td>
					<input type="text" name="ddf_col" class="form-control" placeholder="" value="">
				</td>
			</tr>
			<tr>
				<th>
					Ciudad
				</th>
				<td>
					<input type="text" name="ddf_ciudad" class="form-control" placeholder="" value="">
				</td>
			</tr>
			<tr>
				<th>
					Estado
				</th>
				<td>
					<input type="text" name="ddf_estado" class="form-control" placeholder="" value="">
				</td>
			</tr>
		</table>
	</div>

	<div class="col-md-4">
		<table class="table table-bordered table-striped">
			<tr>
				<th>
					CP
				</th>
				<td>
					<input type="text" name="ddf_cp" class="form-control" placeholder="" value="">
				</td>
			</tr>
			<tr>
				<th>
					Email para Facturación
				</th>
				<td>
					<input type="text" name="ddf_email_para_facturacion" class="form-control" placeholder="" value="">
				</td>
			</tr>
		</table>
		<center>
			<a href="#f5" aria-controls="f5" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-success" aria-label="Left Align">
					<span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> Siguiente
				</button>	
			</a>
		</center>
	</div>
</div>