<table class="table table-striped" style="width:100%;">
	<tr>
		<th>
			<a href="#f1" aria-controls="f1" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> General
				</button>
			</a>
		</th>
		<th>
			<a href="#f2" aria-controls="f2" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-primary">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Terminos de venta
				</button>
			</a>
		</th>
		<th>
			<a href="#f3" aria-controls="f3" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-info">
					<span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span> Usuarios
				</button>
			</a>
		</th>
		<th>
			<a href="#f4" aria-controls="f4" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-default">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Datos de Facturación
				</button>
			</a>
		</th>
		<th>
			<a href="#f5" aria-controls="f5" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-default">
					<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Referencias
				</button>
			</a>
		</th>
	</tr>
</table>
<div class="row">
	<div class="col-md-6">
		<table class="table table-bordered table-striped">
			<tr>
				<th>
					Nombre de usuario
				</th>
				<td>
					<input type="text" name="fd_nombre_de_usuario" class="form-control" placeholder="" value="<?= $nombre_de_usuario ?>">
				</td>
			</tr>
			<tr>
				<th>
					Email de usuario
				</th>
				<td>
					<input type="text" name="fd_email_de_usuario" class="form-control" placeholder="" value="<?= $email_de_usuario ?>">
				</td>
			</tr>
			<tr>
				<th>
					Tel usuario
				</th>
				<td>
					<input type="text" name="fd_tel_usuario" class="form-control" placeholder="" value="<?= $tel_usuario ?>">
				</td>
			</tr>
			<tr>
				<th>
					Puntos interimodel
				</th>
				<td>
					<input type="text" name="fd_puntos_interimodel" class="form-control" placeholder="" value="<?= $puntos_interimodel ?>">
				</td>
			</tr>
			<tr>
				<th>
					Experiencia en software cad
				</th>
				<td>
					<input type="text" name="fd_experiencia_en_software_cad" class="form-control" placeholder="" value="<?= $experiencia_en_software_cad ?>">
				</td>
			</tr>
		</table>
	</div>
	<div class="col-md-6">
		<table class="table table-bordered table-striped">
			<tr>
				<th>
					Software que utiliza
				</th>
				<td>
					<input type="text" name="fd_software_que_utiliza" class="form-control" placeholder="" value="<?= $software_que_utiliza ?>">
				</td>
			</tr>
			<tr>
				<th>
					Sistema operativo
				</th>
				<td>
					<input type="text" name="fd_sistema_operativo" class="form-control" placeholder="" value="<?= $sistema_operativo ?>">
				</td>
			</tr>
			<tr>
				<th>
					Modelado de objetos
				</th>
				<td>
					<input type="text" name="fd_modelado_de_objetos" class="form-control" placeholder="" value="<?= $modelado_de_objetos ?>">
				</td>
			</tr>
			<tr>
				<th>
					Fecha entrega objetos
				</th>
				<td>
					<input type="text" name="fd_fecha_entrega_objetos" class="form-control" placeholder="" value="<?= $fecha_entrega_objetos ?>">
				</td>
			</tr>
		</table>
		<center>
			<a href="#f4" aria-controls="f4" role="tab" data-toggle="tab">
				<button type="button" class="btn btn-success" aria-label="Left Align">
					<span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span> Siguiente
				</button>	
			</a>
		</center>
	</div>
</div>