<br>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12">
		<center>
<?php 
	
	$fechaasignacion = $_GET['fechaasignacion'];
	ini_set('date.timezone', 'America/Chihuahua');
	$horarespuesta = date('H:i a', gmdate('U'));
	$fecharespuesta = date('Y-m-d', gmdate('U'));

?>
			
			<input type="hidden" title="fechaasignacion" name="fechaasignacion" value="<?= $fechaasignacion ?>">

<?php
	
	if ($_SESSION['usuario'] == '') {
		
?>
		<div class="row">
			<div class="col-xs-4 col-sm-4 col-md-4"></div>
			<div class="col-xs-4 col-sm-4 col-md-4">
				<input type="hidden" name="vendedor" readonly="readonly" value="<?= $_GET['vendedor'] ?>" class="form-control">
				<button type="submit" class="btn btn-default" tabindex="17">Aceptar</button>
			</div>
			<div class="col-xs-3 col-sm-3 col-md-3">
				<!-- <span class="label label-danger">Fecha de Captura: <?= '' . $fecharespuesta . ' ' . $horarespuesta . '' ?></span> -->
			</div>
			<div class="col-xs-1 col-sm-1 col-md-1"></div>
		</div>

<?php

	}

	else {

?>
		
		
		<div class="row">
			<div class="col-xs-4 col-sm-4 col-md-4"></div>
			<div class="col-xs-4 col-sm-4 col-md-4">
				<input type="hidden" name="vendedor" readonly="readonly" value="<?= $_GET['vendedor'] ?>" class="form-control">
				<button type="submit" class="btn btn-default" tabindex="17">Aceptar</button>
			</div>
			<div class="col-xs-3 col-sm-3 col-md-3">
				<!-- <span class="label label-danger">Fecha de Captura: <?= '' . $fecharespuesta . ' ' . $horarespuesta . '' ?></span> -->
			</div>
			<div class="col-xs-1 col-sm-1 col-md-1"></div>
		</div>

<?php

	}

?>			

			
		<center>
	</div>
</div>