<table align="center" border="0" cellpadding="0" cellspacing="0" style="background-color: #ffefdb; width: 800px;">
	<tbody>
		<tr>
			<td style="background-image:url('http://avanceytec.com.mx/e-mailing/2015/01/28-anota-un-touchdown-lonas-para-impresion-digital/29-blog.jpg'); width:800px; height:98px;"></td>
		</tr>
		<tr>
			<td>
				<div style="color: #c67300; font-family: century gothic, calibri; font-size: 28px; font-weight: bold; letter-spacing: 0px; margin: 10px 25px; text-align: left; width: 750px;">
					Almacenamiento y cuidados para una mejor impresión
				</div>
				<div style="font-family: century gothic, calibri; font-size: 15px; letter-spacing: 0px; margin: 10px 25px; text-align: justify; width: 750px;">
					La lona debe de estar dentro de su tubo de cartón, con una cubierta de plástico y dos protecciones colocadas en los extremos del alma quedando libre de polvo y humedad, <span style="color: #1f497d; font-weight: bold;">ya que estos factores pueden perjudicar su impresión o cabezales de la impresora.</span>
					<br />
					<br />
					También es recomendable siempre <span style="color: #1f497d; font-weight: bold;">utilizar guantes en el manejo</span> de la lona para evitar contaminarla antes de la impresión.
					<br />
					<br />
					Al adquirir una lona y almacenarla en su negocio se aconseja <span style="color: #1f497d; font-weight: bold;">dejar reposar 24 horas antes de su impresión</span>  para que se adapte a la temperatura ambiente en donde se realizará la impresión (la temperatura ideal es de 21 a 22 grados centígrados).
					<br />
					<br />
					Una vez ya impresa e instalada la lona, se recomienda utilizar <a href="http://www.avanceytec.com.mx/productos/lonas/accesorios-cooley/" style="text-decoration: none;">limpiadores líquidos Cooley<sup><small>®</small></sup></a> especializados para un buen mantenimiento de la aplicación. 
				</div>
			</td>
		</tr>
		<tr>
			<td style="background-image:url('http://avanceytec.com.mx/e-mailing/2015/01/28-anota-un-touchdown-lonas-para-impresion-digital/31-blog.jpg'); width:800px; height:37px;"></td>
		</tr>
	</tbody>
</table>