<?php

	$filtrarporvendedor = $_POST['filtrarporvendedor'];

	$filterDate1E = explode("-", $filterDate1);
	$filterDate1 = ''. $filterDate1E[2]. '-'. $filterDate1E[1] .'-'. $filterDate1E[0] . '';

	$filterDate2E = explode("-", $filterDate2);
	$filterDate2 = ''. $filterDate2E[2]. '-'. $filterDate2E[1] .'-'. $filterDate2E[0] . '';


	if ($filterDate1 == '--') {
		$filterDate1 = '';
	}
	else {
	
	}

	if ($filterDate2 == '--') {
		$filterDate2 = '';
	}
	else {

	}

?>
<div class="row">
	<div class="col-md-6" style="background-color:#ddd;">
		<center><h2>Reporte de Status</h2></center>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12" style="background-color:#fff; padding:2em;">
				<div class="row" >
					<form action="<?= $url ?>" method="post" id="filtrarporfecha">
						<div class="col-md-2 col-lg-2 col-sm-2 col-xs-2">
							<h5>Filtrar por Fecha</h5>
						</div>
						<div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
							<strong>Desde:</strong>
							<div class="input-group input-group-md vista" id="campoparafecha">
								<input type="text" name="filterDate1" onlyread="onlyread" class="form-control datepicker" id="datepickerDesde" placeholder="<?= $filterDate1 ?>" value="<?= $filterDate1 ?>" style="width:140px;" value="<?= $filterDate1 ?>">
							</div>
						</div>
						<div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
							<strong>Hasta:</strong>
							<div class="input-group input-group-md vista" id="campoparafecha">
								<input type="text" name="filterDate2" onlyread="onlyread" class="form-control datepicker" id="datepickerHasta" placeholder="<?= $filterDate2 ?>" value="<?= $filterDate2 ?>" style="width:140px;" value="<?= $filterDate2 ?>">
							</div>
						</div>
						<div class="col-md-2 col-lg-2 col-sm-2 col-xs-2">
							<br>
							<button type="button" class="btn btn-default btn-md" onclick="document.getElementById('filtrarporfecha').submit();" style="margin:auto; margin-right:50px;">
								<span class="glyphicon glyphicon-filter"></span> Filtrar
							</button>
						</div>
						<input type="hidden" name="filtrarporvendedor" value="<?= $filtrarporvendedor ?>">
						<input type="hidden" name="filtrarStatus" value="<?= $filtrarStatus ?>">
					</form>
				</div>
  			</div>
		</div>


		<div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6">
				<?php include('view/v.consultas-graficas.status-equipo.phtml') ?>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6">
				<?php include('view/v.consultas-graficas.status-telemarketing.phtml') ?>
			</div>
		</div>

	</div>


<!--_____________________________________________________________________________________________________________________________________-->



<!-- -->
	<div class="col-md-6" style="box-shadow: -10px 0px 10px gray;">
		<div class="row">
			<div class="col-md-12">
				<?php include('view/v.consultas-graficas.asignaciones.phtml') ?>	
			</div>
		</div>

	
	</div>
<!-- -->

</div>