<h5>Ventas Campo: Asignaciones</h5>
<table class="table table-striped table-bordered" width="100%">
	<tr>
		<td width="30%" style="vertical-align:middle;">
			<div style="width:120px; height120px; margin:auto;">
				
			</div>
		</td>
		<td width="70%">
			<?php
				$a = $consultasEquipo_numero_asignacionesHoy + $consultasEquipo_numero_pendientes;
				$b = $consultasEquipo_numero_asignacionesTotal - $a;
			?>
			<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%;">
				<tr>
					<th style="width:5%;"><span class="label label-info">0</span></th><td style="width:95%;">Para Hoy</td>
				</tr>
				<tr>
					<th class=""><span class="label label-danger">0</span></th><td>Atrasadas</td>
				</tr>
				<tr>
					<th class=""><span class="label label-primary">0</span></th><td>Realizadas</td>
				</tr>
				<tr>
					<th class=""><span class="label" style="background-color:black;">0</span></th><td>Total</td>
				</tr>
			</table>
		</td>
	</tr>
</table>