<div class="modal fade bs-example-modal-lg4" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<!--<div class="modal-dialog modal-lg" style="width:1500px;">-->
	<div class="modal-dialog modal-lg" style="width:100%;">
		<div class="modal-content">
      			<div class="modal-body">
      				<div class="embed-container">
      					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span><span class="sr-only">Close</span></button>
  					<iframe src="if.consultas?iframe=04" width="100%" height="850" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
		</div>
	</div>
</div>