<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="width:1500px; background-color:red;">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">


			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        			<h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-user"></span> Telemarketing</h4>
        				<table class="table table-striped table-condesed table-bordered">
						<tr>
							<th>Posición</th>
							<th>Vendedor</th>
							<th>Facturado</th>
							<th>Correo</th>
							<th>Llamada</th>
							<th>Correo y Llamada</th>
							<th>Descartado</th>
							<th>Bitácora</th>
						</tr>
						<tr class="success">
							<th>1</th>
							<td>Angelica</td>
							<td><?= $total_facturados_angelica ?></td>
							<td><?= $total_correos_angelica ?></td>
							<td><?= $total_llamadas_angelica ?></td>
							<td><?= $total_llamadasycorreos_angelica ?></td>
							<td><?= $total_descartados_angelica ?></td>
							<td>
								<a href="history?vendedor=angelica" style="text-decoration:none; color:black;">
									<button type="button" class="btn btn-primary btn-xs">
										<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
										Ver Bitácora
									</button>
								</a>
							</td>
						</tr>
						<tr>
							<th>2</th>
							<td>Lcera</td>
							<td><?= $total_facturados_lcera ?></td>
							<td><?= $total_correos_lcera ?></td>
							<td><?= $total_llamadas_lcera ?></td>
							<td><?= $total_llamadasycorreos_lcera ?></td>
							<td><?= $total_descartados_lcera ?></td>
							<td>
								<a href="history?vendedor=lcera" style="text-decoration:none; color:black;">
									<button type="button" class="btn btn-primary btn-xs">
										<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
										Ver Bitácora
									</button>
								</a>
							</td>
						</tr>
						<tr>
							<th>3</th>
							<td>Lesparza</td>
							<td><?= $total_facturados_lesparza ?></td>
							<td><?= $total_correos_lesparza ?></td>
							<td><?= $total_llamadas_lesparza ?></td>
							<td><?= $total_llamadasycorreos_lesparza ?></td>
							<td><?= $total_descartados_lesparza ?></td>
							<td>
								<a href="history?vendedor=lesparza" style="text-decoration:none; color:black;">
									<button type="button" class="btn btn-primary btn-xs">
										<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
										Ver Bitácora
									</button>
								</a>
							</td>
						</tr>
						<tr>
							<th>4</th>
							<td>Leticia</td>
							<td><?= $total_facturados_leticia ?></td>
							<td><?= $total_correos_leticia ?></td>
							<td><?= $total_llamadas_leticia ?></td>
							<td><?= $total_llamadasycorreos_leticia ?></td>
							<td><?= $total_descartados_leticia ?></td>
							<td>
								<a href="history?vendedor=leticia" style="text-decoration:none; color:black;">
									<button type="button" class="btn btn-primary btn-xs">
										<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
										Ver Bitácora
									</button>
								</a>
							</td>
						</tr>
						<tr>
							<th>5</th>
							<td>Mario</td>
							<td><?= $total_facturados_mario ?></td>
							<td><?= $total_correos_mario ?></td>
							<td><?= $total_llamadas_mario ?></td>
							<td><?= $total_llamadasycorreos_mario ?></td>
							<td><?= $total_descartados_mario ?></td>
							<td>
								<a href="history?vendedor=mario" style="text-decoration:none; color:black;">
									<button type="button" class="btn btn-primary btn-xs">
										<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
										Ver Bitácora
									</button>
								</a>
							</td>
						</tr>
						<tr>
							<th>6</th>
							<td>Rubi</td>
							<td><?= $total_facturados_rubi ?></td>
							<td><?= $total_correos_rubi ?></td>
							<td><?= $total_llamadas_rubi ?></td>
							<td><?= $total_llamadasycorreos_rubi ?></td>
							<td><?= $total_descartados_rubi ?></td>
							<td>
								<a href="history?vendedor=rubi" style="text-decoration:none; color:black;">
									<button type="button" class="btn btn-primary btn-xs">
										<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
										Ver Bitácora
									</button>
								</a>
							</td>
						</tr>
						<tr>
							<th>7</th>
							<td>Ventascat05</td>
							<td><?= $total_facturados_ventascat05 ?></td>
							<td><?= $total_correos_ventascat05 ?></td>
							<td><?= $total_llamadas_ventascat05 ?></td>
							<td><?= $total_llamadasycorreos_ventascat05 ?></td>
							<td><?= $total_descartados_ventascat05 ?></td>
							<td>
								<a href="history?vendedor=ventascat05" style="text-decoration:none; color:black;">
									<button type="button" class="btn btn-primary btn-xs">
										<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
										Ver Bitácora
									</button>
								</a>
							</td>
						</tr>
						<tr class="danger">
							<th>8</th>
							<td>Ventascat13</td>
							<td><?= $total_facturados_ventascat13 ?></td>
							<td><?= $total_correos_ventascat13 ?></td>
							<td><?= $total_llamadas_ventascat13 ?></td>
							<td><?= $total_llamadasycorreos_ventascat13 ?></td>
							<td><?= $total_descartados_ventascat13 ?></td>
							<td>
								<a href="history?vendedor=ventascat13" style="text-decoration:none; color:black;">
									<button type="button" class="btn btn-primary btn-xs">
										<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
										Ver Bitácora
									</button>
								</a>
							</td>
						</tr>
					</table>
      			</div>
      			<div class="modal-body">
      				<!--
  				<div class="row">
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>Angelica</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:80px; height80px; margin:auto;">
										<canvas id="chart-StatusAngelica" width="80" height="80"/>
									</div>
								</td>
							</tr>
						</table>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>Lcera</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:80px; height80px; margin:auto;">
										<canvas id="chart-StatusLcera" width="80" height="80"/>
									</div>
								</td>
							</tr>
						</table>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>Lesparza</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:80px; height80px; margin:auto;">
										<canvas id="chart-StatusLesparza" width="80" height="80"/>
									</div>
								</td>
							</tr>
						</table>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>Leticia</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:80px; height80px; margin:auto;">
										<canvas id="chart-StatusLeticia" width="80" height="80"/>
									</div>
								</td>
							</tr>
						</table>
					</div>
  				</div>
  				<div class="row">
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>Mario</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:80px; height80px; margin:auto;">
										<canvas id="chart-StatusMario" width="80" height="80"/>
									</div>
								</td>
							</tr>
						</table>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>Rubi</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:80px; height80px; margin:auto;">
										<canvas id="chart-StatusRubi" width="80" height="80"/>
									</div>
								</td>
							</tr>
						</table>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>Ventascat05</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:80px; height80px; margin:auto;">
										<canvas id="chart-StatusVentascat05" width="80" height="80"/>
									</div>
								</td>
							</tr>
						</table>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>Ventascat13</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:80px; height80px; margin:auto;">
										<canvas id="chart-StatusVentascat13" width="80" height="80"/>
									</div>
								</td>
							</tr>
						</table>
					</div>
  				</div>
  			-->

			</div>
			<div class="modal-footer">
        			<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
			</div>

		</div>
	</div>
</div>