<div class="row" style="margin-top:-5px;">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'airigoyen';
			$tmp_Nombre = 'Audelio Irigoyen';
			$tmp_Telefono = 'Ext. 1299';
			$tmp_Correo = 'ventascampodurango@avanceytec.com.mx';

			$tmp_semaforo_Hoy =  $asignacionesHoy_1;
			$tmp_semaforo_Total = $asignacionesTotal_1;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_1;

			$tmp_Grafica = $Datos1;
			$tmp_Grafica_Facturados = $total_facturados_1;
			$tmp_Grafica_Correos = $total_correos_1;
			$tmp_Grafica_Llamadas = $total_llamadas_1;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_1;
			$tmp_Grafica_Descartados = $total_descartados_1;

			$tmp_contactoMedio_01 = $contactoMedio_01_1;
			$tmp_contactoMedio_02 = $contactoMedio_02_1;
			$tmp_contactoMedio_03 = $contactoMedio_03_1;
			$tmp_contactoMedio_04 = $contactoMedio_04_1;
			$tmp_contactoMedio_05 = $contactoMedio_05_1;
			$tmp_contactoMedio_06 = $contactoMedio_06_1;
			$tmp_contactoMedio_07 = $contactoMedio_07_1;
			$tmp_contactoMedio_08 = $contactoMedio_08_1;
			$tmp_contactoMedio_09 = $contactoMedio_09_1;
			$tmp_contactoMedio_10 = $contactoMedio_10_1;

			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'ealvarez';
			$tmp_Nombre = 'Elias Alvarez';
			$tmp_Telefono = 'Ext. 1800';
			$tmp_Correo = '';

			$tmp_semaforo_Hoy =  $asignacionesHoy_2;
			$tmp_semaforo_Total = $asignacionesTotal_2;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_2;

			$tmp_Grafica = $Datos2;
			$tmp_Grafica_Facturados = $total_facturados_2;
			$tmp_Grafica_Correos = $total_correos_2;
			$tmp_Grafica_Llamadas = $total_llamadas_2;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_2;
			$tmp_Grafica_Descartados = $total_descartados_2;

			$tmp_contactoMedio_01 = $contactoMedio_01_2;
			$tmp_contactoMedio_02 = $contactoMedio_02_2;
			$tmp_contactoMedio_03 = $contactoMedio_03_2;
			$tmp_contactoMedio_04 = $contactoMedio_04_2;
			$tmp_contactoMedio_05 = $contactoMedio_05_2;
			$tmp_contactoMedio_06 = $contactoMedio_06_2;
			$tmp_contactoMedio_07 = $contactoMedio_07_2;
			$tmp_contactoMedio_08 = $contactoMedio_08_2;
			$tmp_contactoMedio_09 = $contactoMedio_09_2;
			$tmp_contactoMedio_10 = $contactoMedio_10_2;

			include('v.consultas-graficas-if.02-04.phtml');
		?>

	</div>
</div>
<br>
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'jhernandez';
			$tmp_Nombre = 'jhernandez';
			$tmp_Telefono = 'Ext. ';
			$tmp_Correo = '';

			$tmp_semaforo_Hoy =  $asignacionesHoy_3;
			$tmp_semaforo_Total = $asignacionesTotal_3;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_3;

			$tmp_Grafica = $Datos3;
			$tmp_Grafica_Facturados = $total_facturados_3;
			$tmp_Grafica_Correos = $total_correos_3;
			$tmp_Grafica_Llamadas = $total_llamadas_3;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_3;
			$tmp_Grafica_Descartados = $total_descartados_3;

			$tmp_contactoMedio_01 = $contactoMedio_01_3;
			$tmp_contactoMedio_02 = $contactoMedio_02_3;
			$tmp_contactoMedio_03 = $contactoMedio_03_3;
			$tmp_contactoMedio_04 = $contactoMedio_04_3;
			$tmp_contactoMedio_05 = $contactoMedio_05_3;
			$tmp_contactoMedio_06 = $contactoMedio_06_3;
			$tmp_contactoMedio_07 = $contactoMedio_07_3;
			$tmp_contactoMedio_08 = $contactoMedio_08_3;
			$tmp_contactoMedio_09 = $contactoMedio_09_3;
			$tmp_contactoMedio_10 = $contactoMedio_10_3;

			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'jvazquez';
			$tmp_Nombre = 'Javier Vázquez';
			$tmp_Telefono = 'Ext. ';
			$tmp_Correo = '';

			$tmp_semaforo_Hoy =  $asignacionesHoy_4;
			$tmp_semaforo_Total = $asignacionesTotal_4;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_4;

			$tmp_Grafica = $Datos4;
			$tmp_Grafica_Facturados = $total_facturados_4;
			$tmp_Grafica_Correos = $total_correos_4;
			$tmp_Grafica_Llamadas = $total_llamadas_4;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_4;
			$tmp_Grafica_Descartados = $total_descartados_4;

			$tmp_contactoMedio_01 = $contactoMedio_01_4;
			$tmp_contactoMedio_02 = $contactoMedio_02_4;
			$tmp_contactoMedio_03 = $contactoMedio_03_4;
			$tmp_contactoMedio_04 = $contactoMedio_04_4;
			$tmp_contactoMedio_05 = $contactoMedio_05_4;
			$tmp_contactoMedio_06 = $contactoMedio_06_4;
			$tmp_contactoMedio_07 = $contactoMedio_07_4;
			$tmp_contactoMedio_08 = $contactoMedio_08_4;
			$tmp_contactoMedio_09 = $contactoMedio_09_4;
			$tmp_contactoMedio_10 = $contactoMedio_10_4;

			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
</div>
<br>
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'mramirez';
			$tmp_Nombre = 'Marco Ramirez';
			$tmp_Telefono = 'Ext. 2705';
			$tmp_Correo = 'ventascampotijuana@avanceytec.com.mx';

			$tmp_semaforo_Hoy =  $asignacionesHoy_5;
			$tmp_semaforo_Total = $asignacionesTotal_5;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_5;

			$tmp_Grafica = $Datos5;
			$tmp_Grafica_Facturados = $total_facturados_5;
			$tmp_Grafica_Correos = $total_correos_5;
			$tmp_Grafica_Llamadas = $total_llamadas_5;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_5;
			$tmp_Grafica_Descartados = $total_descartados_5;

			$tmp_contactoMedio_01 = $contactoMedio_01_5;
			$tmp_contactoMedio_02 = $contactoMedio_02_5;
			$tmp_contactoMedio_03 = $contactoMedio_03_5;
			$tmp_contactoMedio_04 = $contactoMedio_04_5;
			$tmp_contactoMedio_05 = $contactoMedio_05_5;
			$tmp_contactoMedio_06 = $contactoMedio_06_5;
			$tmp_contactoMedio_07 = $contactoMedio_07_5;
			$tmp_contactoMedio_08 = $contactoMedio_08_5;
			$tmp_contactoMedio_09 = $contactoMedio_09_5;
			$tmp_contactoMedio_10 = $contactoMedio_10_5;

			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'naguilar';
			$tmp_Nombre = 'Norma Aguilar';
			$tmp_Telefono = 'Ext. 2005';
			$tmp_Correo = 'ventascampotorreon@avanceytec.com.mx';

			$tmp_semaforo_Hoy =  $asignacionesHoy_6;
			$tmp_semaforo_Total = $asignacionesTotal_6;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_6;

			$tmp_Grafica = $Datos6;
			$tmp_Grafica_Facturados = $total_facturados_6;
			$tmp_Grafica_Correos = $total_correos_6;
			$tmp_Grafica_Llamadas = $total_llamadas_6;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_6;
			$tmp_Grafica_Descartados = $total_descartados_6;

			$tmp_contactoMedio_01 = $contactoMedio_01_6;
			$tmp_contactoMedio_02 = $contactoMedio_02_6;
			$tmp_contactoMedio_03 = $contactoMedio_03_6;
			$tmp_contactoMedio_04 = $contactoMedio_04_6;
			$tmp_contactoMedio_05 = $contactoMedio_05_6;
			$tmp_contactoMedio_06 = $contactoMedio_06_6;
			$tmp_contactoMedio_07 = $contactoMedio_07_6;
			$tmp_contactoMedio_08 = $contactoMedio_08_6;
			$tmp_contactoMedio_09 = $contactoMedio_09_6;
			$tmp_contactoMedio_10 = $contactoMedio_10_6;

			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
</div>
<br>
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'rlopez';
			$tmp_Nombre = 'Ramses Lopez ';
			$tmp_Telefono = 'Ext.';
			$tmp_Correo = 'ventascampohermosillo@avanceytec.com.mx';

			$tmp_semaforo_Hoy =  $asignacionesHoy_7;
			$tmp_semaforo_Total = $asignacionesTotal_7;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_7;

			$tmp_Grafica = $Datos7;
			$tmp_Grafica_Facturados = $total_facturados_7;
			$tmp_Grafica_Correos = $total_correos_7;
			$tmp_Grafica_Llamadas = $total_llamadas_7;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_7;
			$tmp_Grafica_Descartados = $total_descartados_7;

			$tmp_contactoMedio_01 = $contactoMedio_01_7;
			$tmp_contactoMedio_02 = $contactoMedio_02_7;
			$tmp_contactoMedio_03 = $contactoMedio_03_7;
			$tmp_contactoMedio_04 = $contactoMedio_04_7;
			$tmp_contactoMedio_05 = $contactoMedio_05_7;
			$tmp_contactoMedio_06 = $contactoMedio_06_7;
			$tmp_contactoMedio_07 = $contactoMedio_07_7;
			$tmp_contactoMedio_08 = $contactoMedio_08_7;
			$tmp_contactoMedio_09 = $contactoMedio_09_7;
			$tmp_contactoMedio_10 = $contactoMedio_10_7;
			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6">
	</div>
</div>