<h5>Servicio al Cliente: Asignaciones</h5>
				<table class="table table-striped table-bordered" width="100%">
					<tr>
						<td width="30%" style="vertical-align:middle;">
							<div style="width:120px; height120px; margin:auto;">
								
								<canvas id="chart-StatusTelemarketingSAC" width="120" height="120" />
							<!---->
							</div>
						</td>
						<td width="70%">
							<?php
								$a = $total_pendientesSAC + $total_facturadosSAC;
								$b = $a;
							?>
							<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%;">
								<tr>
									<th style="width:5%;"><span class="label label-default"><?= $total_pendientesSAC ?></span></th><td style="width:95%;">Pendientes</td>
								</tr>
								<tr>
									<th class=""><span class="label label-success"><?= $total_facturadosSAC ?></span></th><td>Facturados</td>
								</tr>
								<tr>
									<th class=""><span class="label" style="background-color:black;"><?= $b ?></span></th><td>Total</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>