<div class="modal fade bs-example-modal-lg3" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" style="width:1500px;">
		<div class="modal-content">


			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        			<h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-user"></span> Playeras y Gorras Textiles</h4>
      			</div>
      			<div class="modal-body">
  				<div class="row">
					<div class="col-lg-3 col-md-3 col-sm-3">
						<h5>campochihuahua1</h5>
						<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%; ">
							<tr>
								<td style="vertical-align:middle;">
									<div style="width:125px; height125px; margin:auto;">
										<canvas id="chart2-StatusCampochihuahua1" width="125" height="125"/>
									</div>
								</td>
								<td>
									<table class="table table-bordered table-striped table-condensed table-hover" style="width:100%;">
										<tr>
											<th class=""><span class="label label-success"><?= $total_facturados_campochihuahua1 ?></span></th><td>Facturado</td>
										</tr>
										<tr>
											<th class=""><span class="label label-warning"><?= $total_correos_campochihuahua1 ?></span></th><td>Correo</td>
										</tr>
										<tr>
											<th class=""><span class="label label-info"><?= $total_llamadas_campochihuahua1 ?></span></th><td>Llamada</td>
										</tr>
										<tr>
											<th class=""><span class="label label-primary"><?= $total_llamadasycorreos_campochihuahua1 ?></span></th><td>Correo y Llamada</td>
										</tr>
										<tr>
											<th style="width:5%;"><span class="label label-default"><?= $total_descartados_campochihuahua1 ?></span></th><td style="width:95%;">Descartado</td>
										</tr>
										<tr>
											<td style="text-align:center;" colspan="2">
												<a href="history?vendedor=angelica" style="text-decoration:none; color:black;"><button type="button" class="btn btn-default btn-xs" style="margin-top:0px;"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Ver Bitácora</button></a>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
					</div>
					<div class="col-lg-3 col-md-3 col-sm-3">
					</div>
  				</div>

			</div>
			<div class="modal-footer">
        			<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
			</div>

		</div>
	</div>
</div>