<div class="row" style="margin-top:-5px;">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php

			$tmp_Usuario = 'aestrada';
			$tmp_Nombre = 'Andres Estrada';
			$tmp_Telefono = 'Ext. ';
			$tmp_Correo = 'ventascampo3@avanceytec.com.mx';

			$tmp_semaforo_Hoy =  $asignacionesHoy_1;
			$tmp_semaforo_Total = $asignacionesTotal_1;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_1;

			$tmp_Grafica = $Datos1;
			$tmp_Grafica_Facturados = $total_facturados_1;
			$tmp_Grafica_Correos = $total_correos_1;
			$tmp_Grafica_Llamadas = $total_llamadas_1;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_1;
			$tmp_Grafica_Descartados = $total_descartados_1;

			$tmp_contactoMedio_01 = $contactoMedio_01_1;
			$tmp_contactoMedio_02 = $contactoMedio_02_1;
			$tmp_contactoMedio_03 = $contactoMedio_03_1;
			$tmp_contactoMedio_04 = $contactoMedio_04_1;
			$tmp_contactoMedio_05 = $contactoMedio_05_1;
			$tmp_contactoMedio_06 = $contactoMedio_06_1;
			$tmp_contactoMedio_07 = $contactoMedio_07_1;
			$tmp_contactoMedio_08 = $contactoMedio_08_1;
			$tmp_contactoMedio_09 = $contactoMedio_09_1;
			$tmp_contactoMedio_10 = $contactoMedio_10_1;

			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'campojuarez';
			$tmp_Nombre = 'Maria de la Luz Rios';
			$tmp_Telefono = 'Ext. 1800';
			$tmp_Correo = 'campojuarez@avanceytec.com.mx';

			$tmp_semaforo_Hoy =  $asignacionesHoy_2;
			$tmp_semaforo_Total = $asignacionesTotal_2;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_2;

			$tmp_Grafica = $Datos2;
			$tmp_Grafica_Facturados = $total_facturados_2;
			$tmp_Grafica_Correos = $total_correos_2;
			$tmp_Grafica_Llamadas = $total_llamadas_2;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_2;
			$tmp_Grafica_Descartados = $total_descartados_2;

			$tmp_contactoMedio_01 = $contactoMedio_01_2;
			$tmp_contactoMedio_02 = $contactoMedio_02_2;
			$tmp_contactoMedio_03 = $contactoMedio_03_2;
			$tmp_contactoMedio_04 = $contactoMedio_04_2;
			$tmp_contactoMedio_05 = $contactoMedio_05_2;
			$tmp_contactoMedio_06 = $contactoMedio_06_2;
			$tmp_contactoMedio_07 = $contactoMedio_07_2;
			$tmp_contactoMedio_08 = $contactoMedio_08_2;
			$tmp_contactoMedio_09 = $contactoMedio_09_2;
			$tmp_contactoMedio_10 = $contactoMedio_10_2;

			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
</div>
<br>
<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6">
		<?php
			$tmp_Usuario = 'campomonterrey';
			$tmp_Nombre = 'Ezequiel Salas';
			$tmp_Telefono = 'Ext. ';
			$tmp_Correo = 'campomonterrey@avanceytec.com.mx';

			$tmp_semaforo_Hoy =  $asignacionesHoy_3;
			$tmp_semaforo_Total = $asignacionesTotal_3;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_3;

			$tmp_Grafica = $Datos3;
			$tmp_Grafica_Facturados = $total_facturados_3;
			$tmp_Grafica_Correos = $total_correos_3;
			$tmp_Grafica_Llamadas = $total_llamadas_3;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_3;
			$tmp_Grafica_Descartados = $total_descartados_3;

			$tmp_contactoMedio_01 = $contactoMedio_01_3;
			$tmp_contactoMedio_02 = $contactoMedio_02_3;
			$tmp_contactoMedio_03 = $contactoMedio_03_3;
			$tmp_contactoMedio_04 = $contactoMedio_04_3;
			$tmp_contactoMedio_05 = $contactoMedio_05_3;
			$tmp_contactoMedio_06 = $contactoMedio_06_3;
			$tmp_contactoMedio_07 = $contactoMedio_07_3;
			$tmp_contactoMedio_08 = $contactoMedio_08_3;
			$tmp_contactoMedio_09 = $contactoMedio_09_3;
			$tmp_contactoMedio_10 = $contactoMedio_10_3;

			include('v.consultas-graficas-if.02-04.phtml');
			?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6">
			<?php
			$tmp_Usuario = 'ventascamposaltillo';
			$tmp_Nombre = 'Francisco Javier Rodriguez';
			$tmp_Telefono = 'Ext.';
			$tmp_Correo = 'ventascamposaltillo@avanceytec.com.mx';

			$tmp_semaforo_Hoy =  $asignacionesHoy_4;
			$tmp_semaforo_Total = $asignacionesTotal_4;
			$tmp_semaforo_Atrasados = $asignacionesAtrasados_4;

			$tmp_Grafica = $Datos4;
			$tmp_Grafica_Facturados = $total_facturados_4;
			$tmp_Grafica_Correos = $total_correos_4;
			$tmp_Grafica_Llamadas = $total_llamadas_4;
			$tmp_Grafica_Llamadasycorreos = $total_llamadasycorreos_4;
			$tmp_Grafica_Descartados = $total_descartados_4;

			$tmp_contactoMedio_01 = $contactoMedio_01_4;
			$tmp_contactoMedio_02 = $contactoMedio_02_4;
			$tmp_contactoMedio_03 = $contactoMedio_03_4;
			$tmp_contactoMedio_04 = $contactoMedio_04_4;
			$tmp_contactoMedio_05 = $contactoMedio_05_4;
			$tmp_contactoMedio_06 = $contactoMedio_06_4;
			$tmp_contactoMedio_07 = $contactoMedio_07_4;
			$tmp_contactoMedio_08 = $contactoMedio_08_4;
			$tmp_contactoMedio_09 = $contactoMedio_09_4;
			$tmp_contactoMedio_10 = $contactoMedio_10_4;
			include('v.consultas-graficas-if.02-04.phtml');
		?>
	</div>
</div>